import tailwindcss from '@tailwindcss/vite';
import react from '@vitejs/plugin-react';
import path from 'path';
import fs from 'fs';
import {defineConfig, Plugin} from 'vite';

function snippetAutoScannerPlugin(): Plugin {
  const scanDirectory = (dir: string, baseDir: string): any[] => {
    const results: any[] = [];
    if (!fs.existsSync(dir)) return results;

    const entries = fs.readdirSync(dir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      const relativePath = path.relative(baseDir, fullPath).replace(/\\/g, '/');

      if (entry.isDirectory()) {
        results.push(...scanDirectory(fullPath, baseDir));
      } else if (entry.isFile()) {
        const ext = path.extname(entry.name).toLowerCase();
        if (['.html', '.htm', '.svg'].includes(ext)) {
          const fileNameWithoutExt = path.basename(entry.name, ext);
          const parentDir = path.basename(path.dirname(fullPath));

          const cleanTitle = fileNameWithoutExt
            .replace(/[-_]/g, ' ')
            .replace(/([a-z])([A-Z])/g, '$1 $2')
            .trim();
          const title = cleanTitle.charAt(0).toUpperCase() + cleanTitle.slice(1);

          let category = 'other';
          const subfolder = parentDir.toLowerCase();
          if (['buttons', 'button', 'pulsanti'].includes(subfolder)) category = 'buttons';
          else if (['cards', 'card', 'schede'].includes(subfolder)) category = 'cards';
          else if (['navigation', 'nav', 'navbar', 'menu'].includes(subfolder)) category = 'navigation';
          else if (['forms', 'form', 'inputs', 'moduli'].includes(subfolder)) category = 'forms';
          else if (['badges', 'badge', 'tags'].includes(subfolder)) category = 'badges';
          else if (['feedback', 'interactive', 'alerts', 'toast'].includes(subfolder)) category = 'feedback';
          else if (['layout', 'sections', 'headers', 'footers'].includes(subfolder)) category = 'layout';
          else {
            const lowerName = fileNameWithoutExt.toLowerCase();
            if (lowerName.includes('button') || lowerName.includes('btn')) category = 'buttons';
            else if (lowerName.includes('card')) category = 'cards';
            else if (lowerName.includes('nav') || lowerName.includes('menu')) category = 'navigation';
            else if (lowerName.includes('form') || lowerName.includes('input') || lowerName.includes('toggle')) category = 'forms';
            else if (lowerName.includes('badge') || lowerName.includes('pill')) category = 'badges';
          }

          const type = 'html';
          
          let code = '';
          try {
            code = fs.readFileSync(fullPath, 'utf-8');
          } catch (e) {
            console.error('Error reading snippet file:', fullPath, e);
          }

          const tags = [category, 'html'];
          if (code.includes('gradient')) tags.push('gradient');
          if (code.includes('shadow')) tags.push('shadow');
          if (code.includes('dark:')) tags.push('dark-mode');
          if (code.includes('flex')) tags.push('flexbox');
          if (code.includes('grid')) tags.push('grid');
          if (code.includes('<script')) tags.push('interactive');

          results.push({
            id: `file-${relativePath.replace(/[^a-zA-Z0-9_-]/g, '_')}`,
            title,
            description: `Snippet HTML caricato automaticamente da /public/${relativePath}`,
            category,
            type,
            tags: Array.from(new Set(tags)),
            code,
            path: `/${relativePath}`,
            createdAt: new Date().toISOString().split('T')[0],
          });
        }
      }
    }

    return results;
  };

  const syncAutoManifest = (publicSnippetsDir: string) => {
    try {
      if (fs.existsSync(publicSnippetsDir)) {
        const snippets = scanDirectory(publicSnippetsDir, path.resolve(__dirname, 'public'));
        const autoJsonPath = path.join(publicSnippetsDir, 'manifest.json');
        const content = JSON.stringify({
          autoGenerated: true,
          updatedAt: new Date().toISOString(),
          snippets: snippets.map(s => {
            const { code, ...rest } = s;
            return rest;
          })
        }, null, 2);
        fs.writeFileSync(autoJsonPath, content, 'utf-8');
      }
    } catch (err) {
      console.warn('Could not auto-generate manifest.json:', err);
    }
  };

  return {
    name: 'snippet-auto-scanner',
    buildStart() {
      const publicSnippetsDir = path.resolve(__dirname, 'public/snippets');
      syncAutoManifest(publicSnippetsDir);
    },
    configureServer(server) {
      const publicSnippetsDir = path.resolve(__dirname, 'public/snippets');
      syncAutoManifest(publicSnippetsDir);

      server.middlewares.use('/api/scan-snippets', (_req, res) => {
        try {
          const snippets = scanDirectory(publicSnippetsDir, path.resolve(__dirname, 'public'));
          res.setHeader('Content-Type', 'application/json');
          res.setHeader('Cache-Control', 'no-cache');
          res.end(JSON.stringify({ success: true, count: snippets.length, snippets }));
        } catch (error: any) {
          res.statusCode = 500;
          res.setHeader('Content-Type', 'application/json');
          res.end(JSON.stringify({ success: false, error: error?.message || 'Failed to scan' }));
        }
      });
    }
  };
}

export default defineConfig(() => {
  return {
    plugins: [react(), tailwindcss(), snippetAutoScannerPlugin()],
    resolve: {
      alias: {
        '@': path.resolve(__dirname, '.'),
      },
    },
    server: {
      // HMR is disabled in AI Studio via DISABLE_HMR env var.
      // Do not modifyâfile watching is disabled to prevent flickering during agent edits.
      hmr: process.env.DISABLE_HMR !== 'true',
      // Disable file watching when DISABLE_HMR is true to save CPU during agent edits.
      watch: process.env.DISABLE_HMR === 'true' ? null : {},
    },
  };
});
